version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - message-service

  message-service:
    build:
      context: .
      dockerfile: message-service/Dockerfile
    ports:
      - "8081:8081"
